name: Checkout Workflow

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'openjdk'
          java-version: 17

      - name: Build with maven
        run: mvn build